functionsDirectory = "C:\\DEV\\joshburt.com.au\\joshburt.com.au\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
headersOrigin = "config"
redirects = []

[build]
publish = "C:\\DEV\\joshburt.com.au\\joshburt.com.au"
publishOrigin = "config"
commandOrigin = "config"
command = "npm install"
functions = "C:\\DEV\\joshburt.com.au\\joshburt.com.au\\netlify\\functions"

[build.environment]
NODE_VERSION = "22"
DB_DISABLE_SQLITE_FALLBACK = "false"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[plugins]]
origin = "ui"
package = "netlify-purge-cloudflare-on-deploy"
pinned_version = "1"

[plugins.inputs]

[[headers]]
for = "/.netlify/functions/*"

[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
Access-Control-Allow-Methods = "GET, POST, PUT, PATCH, DELETE, OPTIONS"
Access-Control-Max-Age = "86400"

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
X-Content-Type-Options = "nosniff"

[[headers]]
for = "/*.css"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
X-Content-Type-Options = "nosniff"

[[headers]]
for = "/*.js"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
X-Content-Type-Options = "nosniff"

[[headers]]
for = "/*.{jpg,jpeg,png,gif,svg,webp,ico}"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
X-Content-Type-Options = "nosniff"

[[headers]]
for = "/*.html"

[headers.values]
Cache-Control = "public, max-age=3600, must-revalidate"
X-Content-Type-Options = "nosniff"

[[headers]]
for = "/*"

[headers.values]
Strict-Transport-Security = "max-age=15552000; includeSubDomains; preload"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "SAMEORIGIN"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "geolocation=(), microphone=(), camera=(), interest-cohort=()"