functionsDirectory = "C:\\DEV\\joshburt.com.au\\joshburt.com.au\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
headersOrigin = "config"
redirects = []

[build]
publish = "C:\\DEV\\joshburt.com.au\\joshburt.com.au"
publishOrigin = "config"
commandOrigin = "config"
command = "npm install"
functions = "C:\\DEV\\joshburt.com.au\\joshburt.com.au\\netlify\\functions"

[build.environment]
NODE_VERSION = "22"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[plugins]]
origin = "ui"
package = "netlify-purge-cloudflare-on-deploy"
pinned_version = "1"

[plugins.inputs]

[[headers]]
for = "/.netlify/functions/*"

[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
Access-Control-Allow-Methods = "GET, POST, PUT, PATCH, DELETE, OPTIONS"
Access-Control-Max-Age = "86400"