functionsDirectory = "C:\\DEV\\joshburt.com.au\\joshburt.com.au\\.netlify\\functions"

[functions]

[functions."*"]

[[plugins]]
origin = "ui"
package = "netlify-purge-cloudflare-on-deploy"
pinned_version = "1"

[plugins.inputs]

[build]
publish = "C:\\DEV\\joshburt.com.au\\joshburt.com.au"
command = "npm install"
functions = "C:\\DEV\\joshburt.com.au\\joshburt.com.au\\.netlify\\functions"

[build.environment]
NODE_VERSION = "22"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/.netlify/functions/*"

[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Headers = "Content-Type"
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
