headersOrigin = "config"
redirectsOrigin = "config"
plugins = []
functionsDirectory = "C:\\DEV\\joshburt.com.au\\joshburt.com.au\\.netlify\\functions"
functionsDirectoryOrigin = "config-v1"

[functions]

[functions."*"]

[build]
publish = "C:\\DEV\\joshburt.com.au\\joshburt.com.au"
publishOrigin = "config"
commandOrigin = "config"
command = "npm install"
functions = "C:\\DEV\\joshburt.com.au\\joshburt.com.au\\.netlify\\functions"

[build.environment]
NODE_VERSION = "22"
NEON_DATABASE_URL = "postgresql://neondb_owner:npg_RCwEhZ2pm6vx@ep-broad-term-a75jcieo-pooler.ap-southeast-2.aws.neon.tech/neondb?sslmode=require&channel_binding=requireng=require"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/.netlify/functions/*"

[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Headers = "Content-Type"
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]