[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "."

[build.environment]
  NODE_VERSION = "22"
  # Allow SQLite fallback on Netlify when Postgres isn't configured, to avoid 500s on read-only endpoints
  DB_DISABLE_SQLITE_FALLBACK = "false"
  
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Allow-Methods = "GET, POST, PUT, PATCH, DELETE, OPTIONS"
    Access-Control-Max-Age = "86400"

[[headers]]
  # Static assets - Long cache with compression
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

[[headers]]
  # CSS files - Long cache with compression
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

[[headers]]
  # JavaScript files - Long cache with compression
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

[[headers]]
  # Images - Long cache
  for = "/*.{jpg,jpeg,png,gif,svg,webp,ico}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

[[headers]]
  # HTML files - Short cache
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"
    X-Content-Type-Options = "nosniff"

[[headers]]
  # Global security headers for all routes
  for = "/*"
  [headers.values]
    # Enforce HTTPS and enable HSTS for 6 months; includeSubDomains optional depending on subdomain use
    Strict-Transport-Security = "max-age=15552000; includeSubDomains; preload"
    # Prevent MIME type sniffing
    X-Content-Type-Options = "nosniff"
    # Mitigate clickjacking
    X-Frame-Options = "SAMEORIGIN"
    # Limit referrer data
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Conservative permissions policy (expand as needed)
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), interest-cohort=()"
