[build]
  command = "npm install"
  functions = "/.netlify/functions"
  publish = "."

[build.environment]
  NODE_VERSION = "24"
  
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

## Removed legacy Express redirect (/api/* -> functions) after full migration.
