[build]
  publish = "."
  functions = ".netlify/functions"

[dev]
  command = "netlify dev"
  port = 8888
  targetPort = 8000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"

[context.production.environment]
  NEON_DATABASE_URL = "postgresql://neondb_owner:npg_RCwEhZ2pm6vx@ep-broad-term-a75jcieo-pooler.ap-southeast-2.aws.neon.tech/neondb?channel_binding=require&sslmode=require"

[context.dev.environment]
  NEON_DATABASE_URL = "postgresql://neondb_owner:npg_RCwEhZ2pm6vx@ep-broad-term-a75jcieo-pooler.ap-southeast-2.aws.neon.tech/neondb?channel_binding=require&sslmode=require"
